development:
  adapter: postgresql
  encoding: utf8
  database: twitterer_development
  pool: 5
  username: dev
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: twitterer_test
  pool: 5
  username: dev
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: twitterer_production
  pool: 5
  username: dev
  password: 